### PR TITLE
Add i18n Support and Translate to German

### PR DESCRIPTION
**Pull request by pr0gr8mm3r**
This PR adds support for i18n on the calendar page and contributes a translation. It does not include the i18n setup and translation of the settings page.

Thanks for this awesome plugin :)

### CODE REVIEW

**Comment by LuisRodriguezLD** [comment]
Thank you for your PR.
It looks great but could you add instructions on how to switch locales?

**Comment by pr0gr8mm3r** [comment]
Sure. Add 'de' to locale config the backend config like so: https://docs.strapi.io/developer-docs/latest/development/admin-customization.html#configuration-options (Scroll down to "Locales")

Rebuild the admin panel, go to profile settings (click on your username in the Bottom left) and select "German" for Display language.

**Comment by LuisRodriguezLD** [comment]
Thanks for adding the instructions but I meant having them inside the README.md

It seems like the calendar picker is not localized. (see image)
Also, what's the effort on translating the settings page as well?
I feel this could benefit a lot of users and it will be easier to add more languages

Screen Shot 2022-08-28 at 8 19 24 PM

**Comment by LuisRodriguezLD** [comment]
You are right. I guess I just wanted to show _somewhere_ the the plugin is now localizable in German.
I'm good to merge once you resolve the failing action.

**Pull request merged**
