### PR TITLE
Prettier!

### PR DESCRIPTION
**Pull request by schimini**
Well i don´t want to mess with you project too much. but I added prettier to the project. This way, if you guys were interested in anything like this, you could merge this one, and since I've updated my master branch to have all your latest changes + prettier  config + cross-plugin functionality the other merge would be a lot easier to check.

### CODE REVIEW

**Comment by LuisRodriguezLD** [comment]
this is awesome, I love it
shouldn't we either commit a prettierrc file or add config to the package.json?

**Comment by schimini** [comment]
Nice! I think having a prettierrc is good . Right now without it I think it
uses the recommended defaults. I left it like this so that you could
configure it as you like :)

**Comment by LuisRodriguezLD** [comment]
Could you add the [config file](https://github.com/strapi/strapi/blob/main/.prettierrc.js) from the strapi project and reformat?
This will reduce the amount of changes and implement the same style. We should be ready to merge after that

**Comment by schimini** [comment]
@LuisRodriguezLD done :)

**Comment by schimini** [comment]
PS: I tested if was using the config file properly and it is (changed some properties, ran lint and reverted)

**Comment by LuisRodriguezLD** [comment]
Thanks. 
Could you run `yarn lint --fix` again?
The action is failing

**Comment by schimini** [comment]
Sorry i thought I did it :s

**Comment by schimini** [comment]
Btw if I ever take to long to respond, this PR is editable by maintainers so you're free to do what you want :)

**Comment by LuisRodriguezLD** [comment]
Great job. Merging now!

**Pull request merged**
